# Generated by Django 6.0.7 on 2026-08-01 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=160)),
                ('oab', models.CharField(max_length=30, unique=True, verbose_name='Matrícula da OAB')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=25)),
                ('data_admissao', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('resumo_profissional', models.TextField(verbose_name='Contexto histórico')),
                ('formacao', models.TextField(blank=True)),
                ('especialidades', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=140, unique=True)),
                ('categoria', models.CharField(max_length=100)),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('CX', 'Caixa'), ('PCT', 'Pacote'), ('RESMA', 'Resma')], default='UN', max_length=10)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('estoque_minimo', models.PositiveIntegerField(default=0)),
                ('localizacao', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoAdvogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data_evento', models.DateTimeField()),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('advogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='juridico.advogado')),
            ],
            options={
                'ordering': ['-data_evento'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('observacao', models.CharField(blank=True, max_length=250)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='juridico.material')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=40, unique=True, verbose_name='Número do processo')),
                ('titulo', models.CharField(max_length=180)),
                ('area', models.CharField(choices=[('PENAL', 'Direito Penal'), ('TRIBUTARIO', 'Direito Tributário'), ('TRABALHO', 'Direito do Trabalho'), ('CIVIL', 'Direito Civil'), ('FAMILIA', 'Direito de Família'), ('CONSUMIDOR', 'Direito do Consumidor')], max_length=20)),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('EM_ANDAMENTO', 'Em andamento'), ('DEFERIDO', 'Deferido'), ('INDEFERIDO', 'Indeferido'), ('SUSPENSO', 'Suspenso'), ('CONCLUIDO', 'Concluído')], default='NOVO', max_length=20)),
                ('parte_autora', models.CharField(max_length=180)),
                ('parte_re', models.CharField(max_length=180, verbose_name='Parte ré')),
                ('tribunal', models.CharField(blank=True, max_length=150)),
                ('comarca', models.CharField(blank=True, max_length=120)),
                ('data_distribuicao', models.DateField()),
                ('prazo_atual', models.DateTimeField(blank=True, null=True)),
                ('valor_causa', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descricao', models.TextField(blank=True)),
                ('advogado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='juridico.advogado')),
            ],
            options={
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='Andamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data', models.DateTimeField()),
                ('descricao', models.TextField()),
                ('responsavel', models.CharField(blank=True, max_length=150)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andamentos', to='juridico.processo')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
