# Generated by Django 6.0.7 on 2026-08-03 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('arquivo', models.FileField(upload_to='processos/%Y/%m/')),
                ('nome_original', models.CharField(max_length=255)),
                ('texto_extraido', models.TextField(blank=True)),
                ('importado_automaticamente', models.BooleanField(default=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='juridico.processo')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
