# Generated by Django 6.0.7 on 2026-08-03 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0002_documentoprocesso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeticaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('INICIAL', 'Petição inicial'), ('CONTESTACAO', 'Contestação'), ('REPLICA', 'Réplica'), ('RECURSO', 'Recurso'), ('AGRAVO', 'Agravo'), ('MANIFESTACAO', 'Manifestação'), ('CUMPRIMENTO', 'Cumprimento de sentença'), ('EMBARGOS', 'Embargos'), ('OUTROS', 'Outros')], max_length=20)),
                ('objetivo', models.TextField()),
                ('fatos_complementares', models.TextField(blank=True)),
                ('fundamentos_sugeridos', models.TextField(blank=True)),
                ('pedidos_especificos', models.TextField(blank=True)),
                ('orientacoes', models.TextField(blank=True)),
                ('texto_gerado', models.TextField(blank=True)),
                ('modelo_utilizado', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho gerado pela IA'), ('REVISAO', 'Em revisão'), ('APROVADA', 'Aprovada pelo advogado')], default='RASCUNHO', max_length=15)),
                ('revisado_em', models.DateTimeField(blank=True, null=True)),
                ('advogado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peticoes_ia', to='juridico.advogado')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peticoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peticoes_ia', to='juridico.processo')),
            ],
            options={
                'verbose_name': 'Petição elaborada com IA',
                'verbose_name_plural': 'Petições elaboradas com IA',
                'ordering': ['-criado_em'],
            },
        ),
    ]
