# Generated by Django 6.0.7 on 2026-09-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0003_peticaoia'),
    ]

    operations = [
        migrations.AddField(
            model_name='andamento',
            name='status_processo',
            field=models.CharField(blank=True, choices=[('NOVO', 'Novo'), ('EM_ANDAMENTO', 'Em andamento'), ('DEFERIDO', 'Deferido'), ('INDEFERIDO', 'Indeferido'), ('SUSPENSO', 'Suspenso'), ('CONCLUIDO', 'Concluído')], max_length=20, verbose_name='Novo status do processo'),
        ),
    ]
